"""Tests for the local ONNX embedding provider + store (M009/S02).

Uses only the tiny synthetic fixture model (``tests/fixtures/
tiny_embedding_model.onnx``, generated by ``gen_tiny_embedding_model.py``) —
never a real CLIP checkpoint, never a network call. No import in this file
touches ``requests``/``urllib``/``huggingface_hub`` — a source-level guarantee
that no test here can reach the network, not just a runtime one.
"""

from __future__ import annotations

import io
from pathlib import Path

import numpy as np
import pytest
from PIL import Image, ImageDraw

from curator.analysis.compute import ComputeBackend
from curator.catalog import Catalog
from curator.hashing import sha256_hex
from curator.taste.embedding.errors import EmbeddingUnavailableError, EmbeddingVersionError
from curator.taste.embedding.provider import EMBEDDING_DIM, OnnxEmbeddingProvider
from curator.taste.embedding.store import EmbeddingStore, StoredEmbedding, cosine_similarity

FIXTURE_MODEL = Path(__file__).parent / "fixtures" / "tiny_embedding_model.onnx"


def _image_bytes(color: tuple[int, int, int] = (120, 40, 200), fmt: str = "PNG") -> bytes:
    img = Image.new("RGB", (300, 200), color)
    ImageDraw.Draw(img).ellipse([60, 40, 240, 160], fill=(240, 240, 240))
    buf = io.BytesIO()
    img.save(buf, format=fmt)
    return buf.getvalue()


@pytest.fixture
def provider() -> OnnxEmbeddingProvider:
    return OnnxEmbeddingProvider(model_path=FIXTURE_MODEL, model_version="test-fixture-1")


@pytest.fixture
def catalog(data_root) -> Catalog:
    """A migrated Catalog under an isolated data root (schema v17 present)."""
    cat = Catalog(data_root=data_root)
    yield cat
    cat.db.close()


def _register_content(catalog: Catalog, sha: str) -> None:
    """Insert a minimal ``content`` row so FK-constrained embedding inserts succeed."""
    catalog.db.execute("INSERT INTO content(sha256, size) VALUES (?, ?)", (sha, 100))
    catalog.db.commit()


# ---------------------------------------------------------------------------
# capabilities / probe
# ---------------------------------------------------------------------------


def test_capabilities_reports_dim_backend_deterministic_air_gapped(
    provider: OnnxEmbeddingProvider,
) -> None:
    caps = provider.capabilities()
    assert caps.dim == EMBEDDING_DIM == 512
    assert caps.backends == frozenset({ComputeBackend.CPU})
    assert caps.deterministic is True
    assert caps.air_gapped is True


def test_probe_model_absent_reports_ok_false_never_raises(tmp_path: Path) -> None:
    missing = OnnxEmbeddingProvider(model_path=tmp_path / "nonexistent.onnx")
    probe = missing.probe()
    assert probe.ok is False
    assert "not available" in (probe.message or "")


def test_probe_model_present_reports_ok_true(provider: OnnxEmbeddingProvider) -> None:
    probe = provider.probe()
    assert probe.ok is True


def test_probe_checksum_mismatch_reports_ok_false(tmp_path: Path) -> None:
    wrong_hash = "0" * 64
    provider = OnnxEmbeddingProvider(model_path=FIXTURE_MODEL, expected_sha256=wrong_hash)
    probe = provider.probe()
    assert probe.ok is False
    assert "checksum mismatch" in (probe.message or "")


def test_probe_checksum_match_reports_ok_true() -> None:
    correct_hash = sha256_hex(FIXTURE_MODEL.read_bytes())
    provider = OnnxEmbeddingProvider(model_path=FIXTURE_MODEL, expected_sha256=correct_hash)
    assert provider.probe().ok is True


# ---------------------------------------------------------------------------
# determinism
# ---------------------------------------------------------------------------


def test_embed_same_session_bit_identical(provider: OnnxEmbeddingProvider) -> None:
    data = _image_bytes()
    v1 = provider.embed(data)
    v2 = provider.embed(data)
    assert v1.shape == (EMBEDDING_DIM,)
    assert v1.dtype == np.float32
    assert np.array_equal(v1, v2)


def test_embed_fresh_sessions_bit_identical() -> None:
    data = _image_bytes()
    v1 = OnnxEmbeddingProvider(
        model_path=FIXTURE_MODEL, model_version="test-fixture-1"
    ).embed(data)
    v2 = OnnxEmbeddingProvider(
        model_path=FIXTURE_MODEL, model_version="test-fixture-1"
    ).embed(data)
    assert np.array_equal(v1, v2)


def test_embed_is_l2_normalized(provider: OnnxEmbeddingProvider) -> None:
    vector = provider.embed(_image_bytes())
    assert np.linalg.norm(vector) == pytest.approx(1.0, abs=1e-5)


def test_embed_different_images_differ(provider: OnnxEmbeddingProvider) -> None:
    v1 = provider.embed(_image_bytes(color=(120, 40, 200)))
    v2 = provider.embed(_image_bytes(color=(10, 200, 10)))
    assert not np.array_equal(v1, v2)


def test_embed_model_absent_raises_never_returns_vector(tmp_path: Path) -> None:
    missing = OnnxEmbeddingProvider(model_path=tmp_path / "nonexistent.onnx")
    with pytest.raises(EmbeddingUnavailableError):
        missing.embed(_image_bytes())


def test_embed_checksum_mismatch_raises(provider: OnnxEmbeddingProvider) -> None:
    bad = OnnxEmbeddingProvider(model_path=FIXTURE_MODEL, expected_sha256="0" * 64)
    with pytest.raises(EmbeddingUnavailableError):
        bad.embed(_image_bytes())


# ---------------------------------------------------------------------------
# EmbeddingStore
# ---------------------------------------------------------------------------


def test_store_set_get_round_trip(catalog: Catalog) -> None:
    sha = "a" * 64
    _register_content(catalog, sha)
    store = EmbeddingStore(catalog)
    vector = np.random.RandomState(1).uniform(-1, 1, size=(EMBEDDING_DIM,)).astype(np.float32)
    store.set(sha, "v1", vector)
    loaded = store.get(sha, "v1")
    assert loaded is not None
    assert np.allclose(vector, loaded.vector)
    assert loaded.dim == EMBEDDING_DIM
    assert loaded.model_version == "v1"
    assert loaded.sha256 == sha


def test_store_set_upsert_overwrites_in_place(catalog: Catalog) -> None:
    sha = "a" * 64
    _register_content(catalog, sha)
    store = EmbeddingStore(catalog)
    v1 = np.full((EMBEDDING_DIM,), 1.0, dtype=np.float32)
    v2 = np.full((EMBEDDING_DIM,), 2.0, dtype=np.float32)
    store.set(sha, "v1", v1)
    store.set(sha, "v1", v2)
    loaded = store.get(sha, "v1")
    assert loaded is not None
    assert np.array_equal(loaded.vector, v2)
    count = catalog.db.execute(
        "SELECT COUNT(*) FROM content_embeddings WHERE sha256 = ? AND model_version = ?",
        (sha, "v1"),
    ).fetchone()[0]
    assert count == 1


def test_store_get_absent_returns_none(catalog: Catalog) -> None:
    store = EmbeddingStore(catalog)
    assert store.get("b" * 64, "v1") is None


def test_get_matrix_returns_shas_and_matrix_ordered_by_sha(catalog: Catalog) -> None:
    store = EmbeddingStore(catalog)
    vectors = {
        "c" * 64: np.full((EMBEDDING_DIM,), 3.0, dtype=np.float32),
        "a" * 64: np.full((EMBEDDING_DIM,), 1.0, dtype=np.float32),
        "b" * 64: np.full((EMBEDDING_DIM,), 2.0, dtype=np.float32),
    }
    for sha, vec in vectors.items():
        _register_content(catalog, sha)
        store.set(sha, "v1", vec)
    shas, matrix = store.get_matrix("v1")
    assert shas == sorted(vectors)
    assert matrix.shape == (3, EMBEDDING_DIM)
    for i, sha in enumerate(shas):
        assert np.array_equal(matrix[i], vectors[sha])


def test_get_matrix_empty_version_returns_correctly_shaped_empty(catalog: Catalog) -> None:
    store = EmbeddingStore(catalog)
    shas, matrix = store.get_matrix("nonexistent-version")
    assert shas == []
    assert matrix.shape == (0, EMBEDDING_DIM)


# ---------------------------------------------------------------------------
# cosine_similarity / version guard
# ---------------------------------------------------------------------------


def test_cosine_similarity_version_mismatch_raises() -> None:
    v = np.ones((EMBEDDING_DIM,), dtype=np.float32)
    a = StoredEmbedding(
        sha256="a" * 64, model_version="v1", dim=EMBEDDING_DIM, vector=v, created_at=""
    )
    b = StoredEmbedding(
        sha256="b" * 64, model_version="v2", dim=EMBEDDING_DIM, vector=v, created_at=""
    )
    with pytest.raises(EmbeddingVersionError):
        cosine_similarity(a, b)


def test_cosine_similarity_same_version_computes() -> None:
    v1 = np.array([1.0, 0.0], dtype=np.float32)
    v2 = np.array([0.0, 1.0], dtype=np.float32)
    a = StoredEmbedding(sha256="a" * 64, model_version="v1", dim=2, vector=v1, created_at="")
    b = StoredEmbedding(sha256="b" * 64, model_version="v1", dim=2, vector=v2, created_at="")
    assert cosine_similarity(a, b) == pytest.approx(0.0, abs=1e-6)
    assert cosine_similarity(a, a) == pytest.approx(1.0, abs=1e-6)


def test_cosine_similarity_zero_vector_returns_zero_not_nan() -> None:
    """IN-01: a zero-norm vector on either side has no defined direction — must
    return 0.0 ("no similarity"), never NaN from a zero-by-zero division."""
    zero = np.zeros(2, dtype=np.float32)
    v1 = np.array([1.0, 0.0], dtype=np.float32)
    a = StoredEmbedding(sha256="a" * 64, model_version="v1", dim=2, vector=zero, created_at="")
    b = StoredEmbedding(sha256="b" * 64, model_version="v1", dim=2, vector=v1, created_at="")
    assert cosine_similarity(a, b) == 0.0
    assert cosine_similarity(a, a) == 0.0
